# Generated by Django 3.2.7 on 2021-09-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memberships',
            new_name='Membership',
        ),
    ]
